### ISSUE TITLE
Update MS docs: Storage and database related page

### ISSUE THREAD

**Issue by chenrujun** [Azure-Samples/azure-spring-boot-samples#101]
As title.

Please refer to parent issue(#95) to get more information.

**Comment by backwind1233** [comment]
linked pr:https://github.com/chenrujun/azure-dev-docs-pr/pull/6

**Comment by backwind1233** [comment]
linked pr:https://github.com/chenrujun/azure-dev-docs-pr/pull/6

**Comment by saragluna** [comment]
Closing this PR now.
