### ISSUE TITLE
Azure B2C:  Support for Webflux

### ISSUE THREAD

**Issue by jsmwoolf** [Azure-Samples/azure-spring-boot-samples#110]
```
- [ ] bug report -> please search issues before submitting
- [X] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

Would like the ability to use Webflux with the `azure-spring-boot-starter-active-directory-b2c` package.  If this is already supported, how exactly does one use it with Webflux?

**Comment by backwind1233** [comment]
@chenrujun could you help look at this issue

**Comment by chenrujun** [comment]
@jsmwoolf  Thanks for reaching out. Now `azure-spring-boot-starter-active-directory-b2c` does not support web flux.

Now I have a plan to write sample to demonstrate AAD B2C + spring-security + web-flux. This sample will use spring-security, no `azure-spring-boot-starter-active-directory-b2c` included.

Refs: https://github.com/Azure/azure-sdk-for-java/issues/26333

**Comment by chenrujun** [comment]
Closing in favor of https://github.com/Azure/azure-sdk-for-java/issues/21290
