### ISSUE TITLE
[Query] Consumer with Listener for Storage queues

### ISSUE THREAD

**Issue by PunithkumarJagadees** [Azure-Samples/azure-spring-boot-samples#202]
**Query/Question**
I'm looking to implement a consumer with a listener for storage queue. I referred to this branch ( https://github.com/Azure-Samples/azure-spring-boot-samples/tree/main/storage ) and did not find any implementation for listener. Could you please help to find any implementation?

***Why is this not a Bug or a feature Request?***
A clear explanation of why is this not a bug or a feature request?

**Setup (please complete the following information if applicable):**
 - IDE: [e.g. IntelliJ]
 - Library/Libraries: [e.g. com.azure:azure-core:1.16.0 (groupId:artifactId:version)]
 
 **Information Checklist**
 Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [ ] Query Added
- [ ] Setup information Added

**Comment by backwind1233** [comment]
@PunithkumarJagadees thank you for your feedback, I am not sure whether it meets your needs, we use spring integration to receive messages, you can refer to this [link](https://github.com/Azure-Samples/azure-spring-boot-samples/tree/spring-cloud-azure_4.0.0-beta.3/storage/spring-cloud-azure-starter-integration-storage-queue/storage-queue-integration).

**Comment by saragluna** [comment]
Hi @PunithkumarJagadees do you mean message-driven listeners, like the listeners we provide for Event Hubs and Service Bus? Now the storage queue starter doesn't provide such a mechanism for users to register a consumer listener.

**Comment by yiliuTo** [comment]
Close this issue since there is no response for long
