### ISSUE TITLE
Unify Sample's readme template

### ISSUE THREAD

**Issue by backwind1233** [Azure-Samples/azure-spring-boot-samples#26]
Each Sample in this repo should share one common structure or template ,eg: readme
Eg: Readme Structure 
- Goal
- Key concepts
- How to config
  - connectionString
  - service principal
    - Access control (IAM) :assign role
  - msi
- configurable parameters
- Running locally
- deployment
  - Deploy to Azure Spring Cloud

**Comment by chenrujun** [comment]
And the readme in the service /  artifact-id level should be more tutorial like.
One tutorial can include multiple sample applications.
Just like this one: https://spring.io/guides/tutorials/spring-boot-oauth2/

**Comment by backwind1233** [comment]
Closing this issue, duplicated with https://github.com/Azure-Samples/azure-spring-boot-samples/issues/149
