### ISSUE TITLE
[Query]

### ISSUE THREAD

**Issue by Girish662** [Azure-Samples/azure-spring-boot-samples#404]
**Query/Question**
Azure Spring cloud dependency uses default 8080 port while sso redirect can we change the default port to 8443
note : i have use server.port =8443 to change the port but still redirects to port 8080
***Why is this not a Bug or a feature Request?***

**Setup (please complete the following information if applicable):**
- OS: 
- IDE: 
- Sample Path: 
- Library/Libraries: 

**Information Checklist**
 
- [ ] Query Added
- [ ] Setup information Added

**Comment by backwind1233** [comment]
Hi @Girish662, thanks for reaching out.
which library do you use, can you tell us the scenario you use the library?
you said `redirects to port 8080`, do you mean the redirect URL configured in AAD?

I am not very clear about your problem, can you provide more details?

**Comment by stliu** [comment]
@backwind1233 this has been left there for 2 months, we don't have a bot to auto close issues in this repo, right?

Could you check with eng-sys team and see if they could enable the bot for this repo as well?

And update the issue title next time

**Comment by stliu** [comment]
closing since no response from the author for a long time, please create a new issue if you need further help, thanks
