### ISSUE TITLE
[QUERY] Support and documentation about using AzureAD Spring Boot Starter with WebFlux (Reactive Spring)

### ISSUE THREAD

**Issue by ilyas-nordlb** [Azure-Samples/azure-spring-boot-samples#489]
**Query/Question**
Does spring-cloud-azure-starter-active-directory support Webflux (Reactive Spring)? 

Provided example throws following exception when used with Webflux: java.lang.ClassNotFoundException: javax.servlet.Filter

***Why is this not a Bug or a feature Request?***
There is no clear statement about Webflux-Support on documentation pages.

**Setup (please complete the following information if applicable):**
- Sample Path: https://docs.microsoft.com/en-us/azure/developer/java/spring-framework/spring-boot-starter-for-azure-active-directory-developer-guide#protect-a-resource-serverapi
- Library/Libraries: spring-cloud-azure-starter-active-directory 

**Information Checklist**
 
- [ ] Query Added
- [ ] Setup information Added

**Comment by yiliuTo** [comment]
@chenrujun please help to take a look.
