### ISSUE TITLE
Spring-petclinic-microservices integrate with aad

### ISSUE THREAD

**Issue by backwind1233** [Azure-Samples/azure-spring-boot-samples#50]
### Context
After the [PR](https://github.com/Azure-Samples/azure-spring-boot-samples/pull/49) is merged, we can do some checking and integration with aad.

### Goal
1. check that the commented aad code work well
2. integrate with aad after feature 4.0 is released

**Comment by stliu** [comment]
don't have any customer ask for it, closing it for now
