### ISSUE TITLE
Delete all tags after we use spring-cloud-azure-dependencies:4.0.0

### ISSUE THREAD

**Issue by chenrujun** [Azure-Samples/azure-spring-boot-samples#58]
```
<!-- {x-version-update;com.azure.spring:azure-spring-boot-starter-active-directory;dependency} -->
```

Such kind of tag can be deleted after we use spring-cloud-azure-dependencies:4.0.0

**Comment by backwind1233** [comment]
Closing this issue, since all tags begin with `<!-- {x-version-update` have been deleted in main branch.
