### ISSUE TITLE
[FEATURE REQ] Sample for connecting to Azure Database MySQL or PSQL in passwordless way using spring-cloud-azure-starter-jdbc* 

### ISSUE THREAD

**Issue by saragluna** [Azure-Samples/azure-spring-boot-samples#609]
**Is your feature request related to a problem? Please describe.**
The two jdbc starters for Passwordless connections have been [released](https://github.com/Azure/azure-sdk-for-java/blob/main/sdk/spring/CHANGELOG.md#450-2022-12-06):
- spring-cloud-azure-starter-jdbc-mysql:4.5.0
- spring-cloud-azure-starter-jdbc-postgresql:4.5.0

Now we have some samples [here](https://github.com/Azure-Samples/Passwordless-Connections-for-Java-Apps), are we considering adding more samples for Passwordless + JDBC scenarios in this repo or integrate the [Passwordless-Connections-for-Java-Apps](https://github.com/Azure-Samples/Passwordless-Connections-for-Java-Apps) with this one?

**Describe the solution you'd like**
N/A

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Information Checklist**

- [x] Description Added
- [x] Expected solution specified

**Comment by saragluna** [comment]
Deleted this branch https://github.com/Azure-Samples/azure-spring-boot-samples/tree/credential-free.

**Comment by fangjian0423** [comment]
I think integrate SpringBoot part of [Passwordless-Connections-for-Java-Apps repo](https://github.com/Azure-Samples/Passwordless-Connections-for-Java-Apps) is enough. 

@hui1110 could you please help to work on this?
