### ISSUE TITLE
Convert samples to use Spring Boot 3

### ISSUE THREAD

**Issue by vahidhedayati** [Azure-Samples/azure-spring-boot-samples#644]
Hi there at the bottom of README there is information on convert samples to use spring boot 3 but bi
[CONVERT_SAMPLE_TO_USE_SPRING_BOOT_3.md](https://github.com/Azure-Samples/azure-spring-boot-samples/blob/main/CONVERT_SAMPLE_TO_USE_SPRING_BOOT_3_TEMPLATE.md).
[./CONVERT_SAMPLE_TO_USE_SPRING_BOOT_3_TEMPLATE.md](https://github.com/Azure-Samples/azure-spring-boot-samples/blob/main/CONVERT_SAMPLE_TO_USE_SPRING_BOOT_3_TEMPLATE.md).

Contain no real information, are there any sample spring boot 3.0.0 sites sites using  Spring Cloud Azure 5.x

**Comment by chenrujun** [comment]
Hi, @vahidhedayati 

Thanks for reaching out. Sorry for making your confused.
I created a PR to make the description more clear: https://github.com/Azure-Samples/azure-spring-boot-samples/pull/649
Please take a look. Tell me if the description is still not clear enough.

**Comment by fangjian0423** [comment]
hi @vahidhedayati , 

We use profiles to split Spring Boot 2 and Spring Boot 3 support now.

- Profile [spring-cloud-azure-4.x](https://github.com/Azure-Samples/azure-spring-boot-samples/blob/main/pom.xml#L57) used to support Spring Boot 2
- Profile [spring-cloud-azure-5.x](https://github.com/Azure-Samples/azure-spring-boot-samples/blob/main/pom.xml#L166) used to support Spring Boot 3

Check [here](https://github.com/Azure-Samples/azure-spring-boot-samples#all-samples-in-this-repo) to see the support status for Spring Boot 2 and 3.

**Comment by chenrujun** [comment]
Closing this issue.

@vahidhedayati Please add comments here if it's still not clear enough for you.
