### ISSUE TITLE
Update MS doc about how to use Microsoft identity platform in application developed by Spring framework

### ISSUE THREAD

**Issue by chenrujun** [Azure-Samples/azure-spring-boot-samples#67]
### Context

Now here are a lot of MS docs about Managed identity and Spring framework, but these pages didn't give the best solution. For example: these paged should introduce spring-security or spring-cloud-azure-azure-active-directory.

1. Add spring-security related sample here: https://docs.microsoft.com/en-us/azure/active-directory/develop/tutorial-v2-asp-webapp
![image](https://user-images.githubusercontent.com/13167207/203883672-364adb36-f7a8-4005-ae91-b67dde36a9a1.png)

2. Add spring-security related sample here: https://docs.microsoft.com/en-us/azure/developer/java/spring-framework/spring-boot-starter-for-azure-active-directory-developer-guide
![image](https://user-images.githubusercontent.com/13167207/203884023-5ad36065-5a62-4bed-b2ce-e1f25a879fe2.png)

3. Add spring-security related sample here: https://docs.microsoft.com/en-us/azure/active-directory/develop/sample-v2-code

### Problem
Not provide the best solution in these pages may misleading our customers.

### Goal
Make MS docs give the best solution about using Microsoft identity platform in Spring Boot application.

**Comment by stliu** [comment]
>For example: these paged should introduce spring-security or spring-cloud-azure-azure-active-directory.

I don't get your idea here, this link is a tutorial of using asp, why does it should introduce spring-security or spring cloud auzre?
https://docs.microsoft.com/en-us/azure/active-directory/develop/tutorial-v2-asp-webapp

**Comment by chenrujun** [comment]
@stliu 


## 1

> I don't get your idea here, this link is a tutorial of using asp, why does it should introduce spring-security or spring cloud auzre?
> https://docs.microsoft.com/en-us/azure/active-directory/develop/tutorial-v2-asp-webapp

I mean add spring-security related sample here:
![image](https://user-images.githubusercontent.com/13167207/203883672-364adb36-f7a8-4005-ae91-b67dde36a9a1.png)

Since there is no link to `Tutorials` node, I use the first node under `Tutorials` node.
![image](https://user-images.githubusercontent.com/13167207/203883764-06dd64af-711e-47f4-92f2-ac4ee847b7a7.png)

## 2
> the second link is our own doc, what do you mean of should introduce?
> https://docs.microsoft.com/en-us/azure/developer/java/spring-framework/spring-boot-starter-for-azure-active-directory-developer-guide

I mean add spring-security related sample here.
![image](https://user-images.githubusercontent.com/13167207/203884142-e8f7f6a9-b9f0-474b-bfdd-a69491298c12.png)

## 3
> the thrid link does contains our sample, do you find any more issue from it?
> https://learn.microsoft.com/en-us/azure/active-directory/develop/sample-v2-code

1. When the issue is created, the spring-cloud-azure related sample is not added.
2. Beside spring-cloud-azure sample, when I create this issue, I want to add sample about using spring-security.

## Conclusion
Since we already added **spring-cloud-azure** related sample. And you decide not to introduce **spring-security** to our customer, I'll close this issue.
