### ISSUE TITLE
Support For Spring Boot 3 and Security 6

### ISSUE THREAD

**Issue by santiago-cortes-ortiz** [Azure-Samples/azure-spring-boot-samples#672]
Is there an example where aad is used with recent versions of spring boot and security?

**Comment by chenrujun** [comment]
Hi, @santiago-cortes-ortiz 
Thanks for reaching out. Please refer to the README to get more information: https://github.com/Azure-Samples/azure-spring-boot-samples#samples-for-spring-boot-3

**Comment by santiago-cortes-ortiz** [comment]
Lo revisare muchas gracias

**Comment by chenrujun** [comment]
Closing this issue. Because customer's question already been answered.
