### ISSUE TITLE
Add sample for Spring Cloud Gateway + Spring Security OAuth2 + Azure Active Directory.

### ISSUE THREAD

**Issue by chenrujun** [Azure-Samples/azure-spring-boot-samples#69]
Feature request comes from this page: https://spring.io/blog/2021/01/13/the-latest-on-azure-active-directory-integration

**Comment by clavinovahan** [comment]
We also would like to know the solution. Does it work in Azure Spring Cloud?

https://azure.microsoft.com/en-us/services/spring-cloud/

**Comment by chenrujun** [comment]
Hi, @clavinovahan .
Thanks for reaching out.

> We also would like to know the solution. Does it work in Azure Spring Cloud?

Currently, Azure Spring Cloud does not provide Gate Way by default, But customer can setup a Gate Way by himself.
The Gateway in Azure Spring Cloud is under developing.

**Comment by clavinovahan** [comment]
Thanks, @chenrujun. 

We are going to put our own Spring Cloud Gateway implementation with Spring Security OAuth2 and Azure AD on Azure Spring Cloud and runs API behind our gateway. Spring Cloud Gateway is reactive. So based on my understanding, there is no working solution currently for AD and you are working on the solution?

**Comment by chenrujun** [comment]
@clavinovahan 

Thank you for the detailed information.
I set this issue's milestone to `[2021] December`, which means my current plan is to finished this sample before 2021-12-03.

**Comment by clavinovahan** [comment]
@chenrujun.

That is great! We are looking forward to your sample. The earlier the better if possible. Thanks a lot!

**Comment by chenrujun** [comment]
Closing this issue, use this one to track this task: https://github.com/Azure-Samples/spring-boot-application-with-azure-active-directory/issues/4

**Comment by chenrujun** [comment]
Hi, @stliu 
FYI: This is the request about `Spring Cloud Gateway` and `Azure AD`.

**Comment by clavinovahan** [comment]
@chenrujun, could you please update the sample link if it is already done. Thanks.

**Comment by chenrujun** [comment]
@clavinovahan 

Sorry that the sample is not finished yet.
Now we use this issue to track the tasks about creating samples: https://github.com/Azure/azure-sdk-for-java/issues/25817


Hi, @stliu , @seanli1988, 
FYI: Here is another customer ask.
