### ISSUE TITLE
Does this setup support multi-tenant AD apps?

### ISSUE THREAD

**Issue by devlanfear** [Azure-Samples/azure-spring-boot-samples#694]
**Query/Question**
Does this setup support multi-tenant AD apps?

***Why is this not a Bug or a feature Request?***
I tried to configure this sample (web-client-access-resource-server) with tenant id: "common", but this doesn't work.
If it is supported - is there documentation exist for this?

**Comment by moarychan** [comment]
Hi @devlanfear , repeat issue with multi-tenant, I will close this issue, please provide more info at https://github.com/Azure/azure-sdk-for-java/issues/31838 if something missing.
