### ISSUE TITLE
[QUERY] - Sample to use spring.cloud.azure.keyvault.secret.property-sources[0].secret-keys

### ISSUE THREAD

**Issue by andre-uoft** [Azure-Samples/azure-spring-boot-samples#755]
**Query/Question**
I'm using Spring Boot 3.3.2 with Azure KeyVault and I've noticed that when I only want to specify certain secrets using:
`spring.cloud.azure.keyvault.secret.property-sources[0].secret-keys=secret1,secret2` that no secrets are loaded. If I remove the line completely the application will have access to the secret. 

What's the correct way to use `secret-keys` to limit the amount of secrets? 

***Why is this not a Bug or a feature Request?***
Not a bug because I'm not sure what's the correct syntax.

**Information Checklist**
 
- [ x] Query Added
- [ ] Setup information Added

**Comment by saragluna** [comment]
@andre-uoft, how does the secret keys look like? Are they equal to secret names you store in the Key Vault?

**Comment by andre-uoft** [comment]
@saragluna Yes, they are exactly the same names stored in Key Vault. One example name is: `non-prod-mongo-uri`.

**Comment by saragluna** [comment]
@andre-uoft which version are you using?

**Comment by andre-uoft** [comment]
@saragluna These are the dependencies being used:
- Spring Boot 3.3.2

```
	implementation "com.azure.spring:spring-cloud-azure-dependencies:5.14.0"
	implementation "com.azure.spring:spring-cloud-azure-starter-keyvault:5.14.0"
	implementation "com.azure.spring:spring-cloud-azure-autoconfigure:5.14.0"
```

**Comment by moarychan** [comment]
@andre-uoft I can not reproduce this issue, please try with below two ways to specify the secrets:
![image](https://github.com/user-attachments/assets/a3f681c5-fe48-43a9-b728-99b17c1cc48a)

**Comment by saragluna** [comment]
Closed in https://github.com/Azure-Samples/azure-spring-boot-samples/pull/760
