### ISSUE TITLE
[QUERY] Issue send/receive message from servicebus using service principal

### ISSUE THREAD

**Issue by preetishmadalia** [Azure-Samples/azure-spring-boot-samples#757]
**Query/Question**
Followed example provided in 
https://github.com/Azure-Samples/azure-spring-boot-samples/tree/main/servicebus/spring-messaging-azure-servicebus/servicebus-spring-messaging

Unauthorized access. 'Send' claim(s) are required to perform this operation. Resource: 'sb:/****.servicebus.windows.net/****'. 

I was able to verify that the SP has access to send messages. However, I am unable to execute by code with this example.

**Setup (please complete the following information if applicable):**
- OS: Windows
- IDE: IntelliJ
- Sample Path: [](https://github.com/Azure-Samples/azure-spring-boot-samples/tree/main/servicebus/spring-messaging-azure-servicebus/servicebus-spring-messaging)

**Information Checklist**
 
- [x] Query Added
- [ ] Setup information Added

**Comment by saragluna** [comment]
How is the RBAC of the SP configured? Could you make sure they have these role assignments? https://learn.microsoft.com/en-us/azure/developer/java/spring-framework/authentication#authorize-access-with-microsoft-entra-id

**Comment by preetishmadalia** [comment]
Thanks for the response. The SP has data sender role. I found an example with works now.

**Comment by saragluna** [comment]
@preetishmadalia glad to hear that, could you share the example here, for other people who might run into the same issue?

**Comment by preetishmadalia** [comment]
https://github.com/Azure-Samples/azure-spring-boot-samples/blob/main/servicebus/spring-cloud-azure-starter-integration-servicebus/multiple-namespaces/spring2sample/migration-guide.md

**Comment by preetishmadalia** [comment]
Found above example useful.
