### ISSUE TITLE
Update MS docs: Spring Cloud Azure 4.0

### ISSUE THREAD

**Issue by chenrujun** [Azure-Samples/azure-spring-boot-samples#95]
# Target page:
 - https://docs.microsoft.com/en-us/azure/developer/java/spring-framework/
 - GitHub: https://github.com/MicrosoftDocs/azure-dev-docs-pr

**Note** that your PR should be a draft PR before 4.0 GA. And assign @chenrujun as assignee in your created draft PR.

# Tasks

## Before GA release.

1. Update project name to `Spring Cloud Azure`.
2. Update artifactId and version. (4.0 GA version)
3. Update package name / class name.
4. Update property prefix.
5. Add link to reference doc: https://microsoft.github.io/spring-cloud-azure

## After GA release

1. Change link in MS docs into tag instead of version. For example, link to azure-sdk-for-java repo, azure-spring-boot-samples repo.

# Sub Tasks

## Screenshot of sub tasks
![image](https://user-images.githubusercontent.com/13167207/143145131-e078c2ee-680a-4b10-8b3b-9f2499eb9bf1.png)
![image](https://user-images.githubusercontent.com/13167207/143145407-1a93f1e1-a35b-45dd-93c7-fd16ea8417f5.png)

## Sub task table

 - We use one PR to contain all changes: https://github.com/MicrosoftDocs/azure-dev-docs-pr/pull/2487
 - @backwind1233, @yiliuTo , @Netyyyy , @hui1110 , please merge you branch to `chenrujun:spring-cloud-azure_4.0` instead of `master`.
 - Then we can get the preview page in this page: https://review.docs.microsoft.com/en-us/azure/developer/java/spring-framework/?branch=pr-en-us-2487

:x: : Not Finished.
:heavy_check_mark:  : Finished.

| Sub page                                  | GitHub Issue | assignee             | page updated ?        | QA tested?  | 
| --------------------------------- | -------------- | ------------------ | ----------------          | -------------- |
| Spring on Azure                       | #97                | @Netyyyy           | :heavy_check_mark: | :x:                  | 
| Spring Boot Starters for Azure | #98                | @hui1110           | :heavy_check_mark: | :x:                  | 
| Spring Security                         | #99                |@chenrujun         | :x:                             | :x:                  | 
| Messaging                                | #100              | @yiliuTo              | :x:                             | :x:                  | 
| Storage and database              | #101              | @backwind1233 | :heavy_check_mark:  | :x:                  | 

 - [x] #97  @Netyyyy 
 - [x] #98  @hui1110 
 - [x] #99  @chenrujun 
 - [ ] #100  @yiliuTo 
 - [x] #101  @backwind1233 
 - [x] #102  @saragluna

**Comment by chenrujun** [comment]
Hi, @backwind1233 , @saragluna , @yiliuTo . Could you please finish this task before 2021-12-10?

**Comment by chenrujun** [comment]
Hi, @backwind1233 , @saragluna , @yiliuTo , @Netyyyy , @hui1110 

**Note** that your PR should be a draft PR before 4.0 GA. And assign @chenrujun as assignee in your created draft PR.

**Comment by saragluna** [comment]
The app configuration isn't in our 4.0 scope, so I think the docs don't need to be updated for app configuration?

**Comment by chenrujun** [comment]
@saragluna Thank you for your information. I closed related sub task just now.

**Comment by chenrujun** [comment]
Hi, @backwind1233 , @saragluna , @yiliuTo , @Netyyyy , @hui1110 .
Please finish this task before 2021-12-09, we need to let QA team test it before let Docs team review this PR.

**Comment by chenrujun** [comment]
Hi, @backwind1233 , @saragluna , @yiliuTo , @Netyyyy , @hui1110 .

I created a new PR: https://github.com/MicrosoftDocs/azure-dev-docs-pr/pull/2487
Please merge you branch to `chenrujun:spring-cloud-azure_4.0` instead of `master`.
So that we can get the preview page in this page: https://review.docs.microsoft.com/en-us/azure/developer/java/spring-framework/configure-spring-app-with-cosmos-db-on-app-service-linux?branch=pr-en-us-2487

**Comment by saragluna** [comment]
Close in favor of https://github.com/Azure/azure-sdk-for-java/issues/26307.
